name=ESP32ControlLogix
version=0.1.0
author=Xorlent
maintainer=Xorlent <https://github.com/Xorlent>
sentence=Native ESP32 Allen-Bradley ControlLogix EtherNet/IP and CIP client.
paragraph=ESP32-Arduino ControlLogix EtherNet/IP/CIP protocol implementation.
category=Communication
url=https://github.com/Xorlent/ESP32-ControlLogix
architectures=esp32
includes=ESP32ControlLogix.h